### PR TITLE
Feature/178: Fix PythonControlledCapability #178

### LINKED ISSUE #178: Python wrappers break with new material ui
PythonControlledCapability.js the following line breaks with new material-ui components
```
class PythonControlledComponent extends WrappedComponent {
```

This is needed to port netpyne to new geppetto-client version @ddelpiano .

### PR DESCRIPTION
**Pull request by filippomc**
Closes #178 #209

### CODE REVIEW

File: js/components/interface/flexLayout2/src/view/BorderButton.tsx [hunk 1]
```diff
@@ -79,7 +80,13 @@ export class BorderButton extends React.Component<IBorderButtonProps, any> {
         let leadingContent = undefined;
 
         if (node.getIcon() !== undefined) {
-            leadingContent = <img src={node.getIcon()}/>;
+            if (node.getIcon().startsWith('fa ')) {
```
Comment (ddelpiano) [inline js/components/interface/flexLayout2/src/view/BorderButton.tsx:83]: Do we really need to alterate flexlayout for this since we can already achieve this with onRenderTabSet and inject whatever icon we want?

File: js/components/interface/flexLayout2/src/view/TabButton.tsx [hunk 2]
```diff
@@ -130,7 +130,13 @@ export class TabButton extends React.Component<ITabButtonProps, any> {
         let leadingContent = undefined;
 
         if (node.getIcon() !== undefined) {
-            leadingContent = <img src={node.getIcon()} />;
+            if (node.getIcon().startsWith('fa ')) {
```
Comment (ddelpiano) [inline js/components/interface/flexLayout2/src/view/TabButton.tsx:133]: Same note here, do we really need to import material in flexlayout when we can achieve this injecting the icons with onRenderTabSet ?

File: js/communication/geppettoJupyter/PythonControlledCapability.js [hunk 3]
```diff
@@ -163,13 +178,16 @@ define(function (require) {
...
               break;
             }
+            // Don't sync if new value is emtpy string
             if (newValue !== '') {
-              this.syncValueWithPython(newValue);
-              if (this.props.callback) {
-                this.props.callback(newValue, this.oldValue === undefined ? this.state.value : this.oldValue);
-                this.oldValue = newValue;
-              }
+              this.syncValueWithPython(newValue, this.oldValue);
```
Comment (ddelpiano) [inline js/communication/geppettoJupyter/PythonControlledCapability.js:183]: just curious about this, are we now comparing new and old value in the handler function provided?

File: js/communication/geppettoJupyter/PythonControlledCapability.js [hunk 4]
```diff
@@ -13,15 +13,26 @@ define(function (require) {
...
+      
       class PythonControlledComponent extends WrappedComponent {
         constructor (props) {
           super(props);
           if (this.state == undefined) {
             this.state = {};
           }
           this.state.model = props.model;
-          this.state.componentType = WrappedComponent.name;
+          this.state.componentType = WrappedComponent.name || WrappedComponent.Naked.render.name;
```
Comment (ddelpiano) [inline js/communication/geppettoJupyter/PythonControlledCapability.js:33]: this can be wrapped by a getter in case the HOC wrapper needs to get base component from different libraries, just a suggestion, no need to change it now but I will place a comment in the code for the future.

File: js/communication/geppettoJupyter/PythonControlledCapability.js (hunk 3 above)
Comment (ddelpiano) [reply js/communication/geppettoJupyter/PythonControlledCapability.js:183]: Also, could we add some comment here on why are we passing new and old so at least who read this code for the first time has an idea of what happens underneath? Thx.

File: js/communication/geppettoJupyter/PythonControlledCapability.js [hunk 5]
```diff
@@ -251,6 +273,7 @@ define(function (require) {
           default:
             wrappedComponentProps['onChange'] = this.handleChange;
             wrappedComponentProps['value'] = (typeof this.state.value === 'object' && this.state.value !== null && !Array.isArray(this.state.value)) ? JSON.stringify(this.state.value) : this.state.value;
+            wrappedComponentProps.value = wrappedComponentProps.multiple && wrappedComponentProps.value !== undefined && !wrappedComponentProps.value ? [] : wrappedComponentProps.value;
```
Comment (ddelpiano) [inline js/communication/geppettoJupyter/PythonControlledCapability.js:276]: I would add a comment here, too many conditions, difficult to follow.

File: js/communication/geppettoJupyter/PythonControlledCapability.js [hunk 6]
```diff
@@ -13,15 +13,26 @@ define(function (require) {
 
   module.exports = {
     createPythonControlledComponent (WrappedComponent) {
+      if (typeof WrappedComponent !== "function") {
```
Comment (ddelpiano) [inline js/communication/geppettoJupyter/PythonControlledCapability.js:16]: I get what is happening since I already worked with this module but a comment here to explain what is happening would not harm :)

File: js/components/interface/flexLayout2/src/view/BorderButton.tsx (hunk 1 above)
Comment (filippomc) [reply js/components/interface/flexLayout2/src/view/BorderButton.tsx:83]: @rodriguez-facundo

File: js/communication/geppettoJupyter/PythonControlledCapability.js (hunk 6 above)
Comment (filippomc) [reply js/communication/geppettoJupyter/PythonControlledCapability.js:16]: The comment is up there: ` // Fixes components defined as objects (e.g. Material-ui components)`

File: js/communication/geppettoJupyter/PythonControlledCapability.js (hunk 4 above)
Comment (filippomc) [reply js/communication/geppettoJupyter/PythonControlledCapability.js:33]: Where do you suggest to have the getter? The `PythonControlledComponent` class?

Comment (ddelpiano) [reply js/communication/geppettoJupyter/PythonControlledCapability.js:33]: yes

File: js/communication/geppettoJupyter/PythonControlledCapability.js (hunk 3 above)
Comment (rodriguez-facundo) [reply js/communication/geppettoJupyter/PythonControlledCapability.js]: My bad. Removed the line. Probably I mixed up with the callback

File: js/components/interface/flexLayout2/src/view/BorderButton.tsx (hunk 1 above)
Comment (rodriguez-facundo) [reply js/components/interface/flexLayout2/src/view/BorderButton.tsx]: Removed

File: js/components/interface/flexLayout2/src/view/TabButton.tsx (hunk 2 above)
Comment (rodriguez-facundo) [reply js/components/interface/flexLayout2/src/view/TabButton.tsx]: Removed
