### PR TITLE
Fixed slideShowImageComponent checkbox to work also with instances without visual capabilities

### LINKED ISSUE #302: customComponent slideShowImage checkbox not working with non visual instances

### PR DESCRIPTION
**Pull request by ddelpiano**
Added on top of the PRs [299](https://github.com/openworm/geppetto-client/pull/299) and [301](https://github.com/openworm/geppetto-client/pull/301), these should go before this one.

### CODE REVIEW

**Review by filippomc — APPROVED** [review]

File: js/components/interface/query/customComponents/slideshowImageComponent.js [hunk 1]
```diff
@@ -11,18 +11,20 @@ define(function (require) {
     constructor (props) {
       super(props);
 
+      console.log("sto inizializzando il slideshow per l istanza " + this.props.rowData.id);
```
Comment (tarelli) [inline js/components/interface/query/customComponents/slideshowImageComponent.js:14]: @ddelpiano should this be debug? also change to English :)

File: js/components/interface/query/customComponents/slideshowImageComponent.js [hunk 2]
```diff
@@ -38,10 +40,14 @@ define(function (require) {
...
-          initialCheckBoxState = imageVariable.isVisible();
+          if (imageVariable.hasCapability(GEPPETTO.Resources.VISUAL_CAPABILITY)) {
+            initialCheckBoxState = imageVariable.isVisible();
+          } else {
+            initialCheckBoxState = true;
+          }
         }
       } catch (e) {
-        console.info("Instance Variable not Found : " + path); 
+        console.info("Instance Variable not Found : " + path);
```
Comment (tarelli) [inline js/components/interface/query/customComponents/slideshowImageComponent.js:50]: @ddelpiano should this be warn?
